Done second part of homework.
Jyugo009/CourseProjectOOP pull request #2
Opened 2023-11-28 15:09 UTC by Jyugo009

2023-11-28 18:23 UTC, Delvin09 requested changes

2023-11-28 18:23 UTC, Delvin09 commented on Interfaces/IBinarySearchTree.cs
> +namespace Interfaces
MyClassLibrary.Interfaces

2023-11-28 18:23 UTC, Delvin09 commented on Interfaces/IQueue.cs
> +        {
давай без такого, можно просто убрать метод Add из ICollections

2023-11-28 18:23 UTC, Delvin09 commented on Interfaces/IBinarySearchTree.cs
> +    public interface IBinarySearchTree : ICollections
Если оставлять метод Add в ICollections, то нет смысла в интерфейсе IBinarySearchTree

2023-11-28 18:23 UTC, Delvin09 commented on Interfaces/ICollections.cs
> +    public interface ICollections
ICollections -> ICollection

2023-11-28 18:23 UTC, Delvin09 commented on MyClassLibrary/MyQueue.cs
> +            throw new NotImplementedException();
вызови Enqueue, а метод реализуй явно: void ICollection.Add(object item)
и в стеке, подобным образом поправь

2023-11-29 05:37 UTC, Jyugo009 commented on Interfaces/IBinarySearchTree.cs
> +namespace Interfaces
+

2023-11-29 05:46 UTC, Jyugo009 commented on Interfaces/IQueue.cs
> +        {
+

2023-11-29 05:46 UTC, Jyugo009 commented on Interfaces/IBinarySearchTree.cs
> +    public interface IBinarySearchTree : ICollections
+

2023-11-29 05:46 UTC, Jyugo009 commented on Interfaces/ICollections.cs
> +    public interface ICollections
+

2023-11-29 05:48 UTC, Jyugo009 commented on MyClassLibrary/MyQueue.cs
> +            throw new NotImplementedException();
Убрал метод Add из ICollection и добавив его только в нужные интерфейсы - избежал этого.

2023-11-29 14:04 UTC, Delvin09 approved these changes

2023-11-29 14:04 UTC, Delvin09 commented on Interfaces/IDoubleLinkedList.cs
>          public object? First { get; }
В интерфейсах обычно не указывают модификаторы доступа

2023-11-29 14:04 UTC, Delvin09 commented on Interfaces/IDoubleLinkedList.cs
> +    public interface IDoubleLinkedList : ICollection
можно расширить интерфейс односвязного списка.

2023-11-29 15:15 UTC, Jyugo009 commented on Interfaces/IDoubleLinkedList.cs
>          public object? First { get; }
+

2023-12-07 18:36 UTC, merged