Events done
Jyugo009/CourseProjectOOP pull request #4
Opened 2023-12-11 17:10 UTC by Jyugo009

2023-12-11 21:50 UTC, Delvin09 requested changes

2023-12-11 21:50 UTC, Delvin09 commented on MyClassLibrary/ObservedList.cs
> +        public event EventHandler<ListChangedEventArgs<T>> ItemAdded;
События обычно располагают в самом конце

2023-12-11 21:50 UTC, Delvin09 commented on MyClassLibrary/ObservedList.cs
> +        public new void Add(T? item)
не нужно делать new, просто сделай методы виртуальными в базовом классе, а тут перегрузи

2023-12-11 21:50 UTC, Delvin09 commented on MyClassLibrary/MyList.cs
> +        protected T?[] _items;
если сделать виртуальные методы и перегрузить их, то в protected полях нет нужды.

2023-12-12 06:30 UTC, Jyugo009 commented on MyClassLibrary/ObservedList.cs
> +        public event EventHandler<ListChangedEventArgs<T>> ItemAdded;
+

2023-12-12 06:34 UTC, Jyugo009 commented on MyClassLibrary/ObservedList.cs
> +        public new void Add(T? item)
+

2023-12-12 06:53 UTC, Jyugo009 commented on MyClassLibrary/MyList.cs
> +        protected T?[] _items;
+

2023-12-12 09:52 UTC, Delvin09 approved these changes

2023-12-12 09:56 UTC, merged